/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ActionOulineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ActionOulineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="M10.506 4h3v5.403l4.678-2.7 1.5 2.597-4.678 2.7 4.678 2.7-1.5 2.597-4.678-2.7V20h-3v-5.403l-4.678 2.7-1.5-2.597L9.006 12 4.328 9.3l1.5-2.597 4.678 2.7z"
      />
    </svg>
  )
}
export default ActionOulineIcon
