/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ArrowDownOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ArrowDownOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="m11.162 21.25.847.847.848-.847 6-6 .847-.848-1.699-1.698-4.8 4.8V2.402h-2.4v15.102q-4.725-4.726-4.8-4.8l-1.698 1.698.847.848 6 6z"
      />
    </svg>
  )
}
export default ArrowDownOutlineIcon
