/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function CheckboxOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="CheckboxOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path fill="currentColor" fillOpacity={0.9} d="M18.6 5.4v13.2H5.4V5.4zM5.4 3.6H3.6v16.8h16.8V3.6z" />
    </svg>
  )
}
export default CheckboxOutlineIcon
