/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ChevronLeftOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ChevronLeftOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="m6.71 12 .848.847 6 6 .848.847 1.699-1.698-6-6 5.152-5.153.848-.847-1.7-1.7-.847.848-6 6-.847.848z"
      />
    </svg>
  )
}
export default ChevronLeftOutlineIcon
