/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function CompassFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="CompassFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="M2.4 12A9.6 9.6 0 0 1 12 2.4a9.6 9.6 0 0 1 9.6 9.6 9.6 9.6 0 0 1-9.6 9.6A9.6 9.6 0 0 1 2.4 12m6.9-2.7-2.1 7.5 7.5-2.1 2.1-7.5zm2.7 1.5a1.199 1.199 0 1 1 0 2.4c-.664 0-1.2-.536-1.2-1.2s.536-1.2 1.2-1.2"
      />
    </svg>
  )
}
export default CompassFillIcon
