/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function EllipsisOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="EllipsisOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="M14.098 3.602h-4.2v4.2h4.2zm-4.2 6.3v4.2h4.2v-4.2zm0 6.3v4.2h4.2v-4.2z"
      />
    </svg>
  )
}
export default EllipsisOutlineIcon
