/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function HeartFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="HeartFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="M7.391 3.6c1.601 0 3.109.769 4.047 2.066l.562.776.563-.776A4.992 4.992 0 0 1 21.6 8.591c-.001 5.13-5.757 9.758-9.601 12.409-3.844-2.651-9.6-7.279-9.6-12.409A4.99 4.99 0 0 1 7.391 3.6"
      />
    </svg>
  )
}
export default HeartFillIcon
