/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function LockFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="LockFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="M12 1.2A4.8 4.8 0 0 1 16.8 6v2.4h2.4v13.2H4.8V8.4h2.4V6A4.8 4.8 0 0 1 12 1.2m1.316 11.828c-.457 0-.887.22-1.155.591l-.161.222-.16-.222a1.428 1.428 0 0 0-2.583.836c0 1.466 1.645 2.788 2.743 3.545 1.098-.757 2.743-2.08 2.743-3.545 0-.787-.64-1.427-1.427-1.427M12 3.6A2.403 2.403 0 0 0 9.6 6v2.4h4.8V6c0-1.324-1.076-2.4-2.4-2.4"
      />
    </svg>
  )
}
export default LockFillIcon
