/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function MessageSmileOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="MessageSmileOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="M2.4 3.6v15.6h4.8v3.6l6-3.6h8.4V3.6zm7.2 4.8c.664 0 1.2.536 1.2 1.2s-.536 1.2-1.2 1.2-1.2-.536-1.2-1.2.536-1.2 1.2-1.2m4.8 0c.664 0 1.2.536 1.2 1.2s-.536 1.2-1.2 1.2a1.199 1.199 0 1 1 0-2.4m-5.752 4.5A4.48 4.48 0 0 0 12 14.4a4.48 4.48 0 0 0 3.352-1.5l1.343 1.2A6.3 6.3 0 0 1 12 16.2a6.3 6.3 0 0 1-4.695-2.1z"
      />
    </svg>
  )
}
export default MessageSmileOutlineIcon
