/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function NavCommentFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="NavCommentFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="M7 3h16v14l-4.5-3V8.25a.75.75 0 0 0-.75-.75h-6a.75.75 0 1 0 0 1.5H17v11H9.5L5 23v-3H1V9h6z"
      />
    </svg>
  )
}
export default NavCommentFillIcon
