/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function NavHomeFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="NavHomeFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path fill="currentColor" fillOpacity={0.9} d="M12.75 21H21V9l-9-8-9 8v12h8.25v-6.25a.75.75 0 1 1 1.5 0z" />
    </svg>
  )
}
export default NavHomeFillIcon
