/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function RecreateOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="RecreateOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="M21.6 9.6V2.1l-2.963 2.963c-3.76-3.6-9.727-3.552-13.425.15a9.58 9.58 0 0 0-2.808 7.042 9.587 9.587 0 0 0 2.809 6.533A9.57 9.57 0 0 0 12 21.6a9.6 9.6 0 0 0 8.58-5.291l-2.145-1.08A7.2 7.2 0 0 1 12 19.196a7.21 7.21 0 0 1-6.818-4.875 7.2 7.2 0 0 1-.378-2.073q-.005-.126-.004-.255a7.2 7.2 0 0 1 12.139-5.239L14.1 9.6z"
      />
    </svg>
  )
}
export default RecreateOutlineIcon
