/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ThumbsDownOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ThumbsDownOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="M18.6 3.6v1.8h.6v2.4h.6v2.4h.6v6h-6.847l1.87 3.742-.802.402-3.757 1.878-.807.402q-.269-.537-1.342-2.681L7.8 18.109v.491H2.4V6h4.301l.709-.442 2.4-1.5.51-.32.217-.134h8.06zm-7.545 1.8-.293.184-2.4 1.5-.562.352v6.649l2.524 5.051.536 1.076 2.145-1.072q-1.982-3.965-2.366-4.736h7.957v-2.4h-.6v-2.4h-.6v-2.4h-.6v-1.8h-5.745zM4.2 7.8v9H6v-9z"
      />
    </svg>
  )
}
export default ThumbsDownOutlineIcon
