/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ThumbsDownFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ThumbsDownFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="M18.6 3.6V6h1.2v2.4h.6v3h.6v4.2h-7.8l1.8 3.6-3.6 1.8-3-5.4V6L12 3.6zM6.6 6v12H2.4V6z"
      />
    </svg>
  )
}
export default ThumbsDownFillIcon
