/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function WandMagicFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="WandMagicFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillOpacity={0.9}
        d="m11 7.5-.75-1.75L8.5 5l1.75-.75L11 2.5l.75 1.75L13.5 5l-1.75.75zM2.5 8 5 7l1-2.5L7 7l2.5 1L7 9l-1 2.5L5 9zm14 7.5 1-2.5 1 2.5 2.5 1-2.5 1-1 2.5-1-2.5-2.5-1zm1-11.916L20.416 6.5l-3.678 3.678-2.916-2.916zM3.584 17.5l9.179-9.178 2.915 2.916L6.5 20.416z"
      />
    </svg>
  )
}
export default WandMagicFillIcon
