/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function AiFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="AiFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M18.992 4.5h-.5a1 1 0 0 0-1 1V6a1 1 0 0 0 1 1h.5a1 1 0 0 0 1-1v-.5a1 1 0 0 0-1-1m.5 3.5h-1.5a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h1.5a.5.5 0 0 0 .5-.5v-10a.5.5 0 0 0-.5-.5M7.736 6.1c.224-.66.828-1.1 1.51-1.1h.01c.681 0 1.285.44 1.509 1.1l4.714 12.35c.087.27-.107.55-.38.55H13.54a.4.4 0 0 1-.38-.27l-1.003-2.76a.41.41 0 0 0-.38-.27H6.723a.4.4 0 0 0-.38.27L5.34 18.73a.41.41 0 0 1-.38.27H3.402c-.283 0-.468-.28-.38-.55zm-1.013 5.49c1.276.26 2.27 1.28 2.522 2.59.254-1.31 1.247-2.33 2.523-2.59-1.276-.26-2.27-1.28-2.523-2.59-.253 1.31-1.246 2.33-2.522 2.59"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default AiFillIcon
