/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ArrowUpOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ArrowUpOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        d="M11.713 5.807a.8.8 0 0 0-.243.163l-5 5a.75.75 0 1 0 1.06 1.06l3.72-3.72v9.19a.75.75 0 0 0 1.5 0V8.31l3.72 3.72a.75.75 0 1 0 1.06-1.06l-5-5a.75.75 0 0 0-.817-.163"
      />
    </svg>
  )
}
export default ArrowUpOutlineIcon
