/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ArrowRightOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ArrowRightOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        d="M18.193 11.713a.8.8 0 0 0-.163-.243l-5-5a.75.75 0 1 0-1.06 1.06l3.72 3.72H6.5a.75.75 0 0 0 0 1.5h9.19l-3.72 3.72a.75.75 0 1 0 1.06 1.06l5-5a.75.75 0 0 0 .163-.817"
      />
    </svg>
  )
}
export default ArrowRightOutlineIcon
