/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function CallDeclineOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="CallDeclineOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path
          fillRule="evenodd"
          d="M10.042 12.544a8.4 8.4 0 0 1-1.287-2.294l-.017-.046-.03-.058a.39.39 0 0 1 .105-.39l1.534-1.535.007-.008c.673-.704.694-1.844-.014-2.552L7.245 2.567l-.007-.007c-.705-.673-1.844-.693-2.552.014L3.673 3.587A4.9 4.9 0 0 0 2.48 5.455c-.813 2.327-.362 5.983 4.007 10.644l-4.145 4.144a1 1 0 1 0 1.415 1.415l17-17a1 1 0 0 0-1.415-1.415zM5.955 3.85 4.946 4.86a3.1 3.1 0 0 0-.764 1.182l-.002.005c-.51 1.457-.485 4.427 3.58 8.779l1.001-1.002a10.2 10.2 0 0 1-1.677-2.902l-.032-.064-.016-.043a2.19 2.19 0 0 1 .504-2.333l1.515-1.514a.05.05 0 0 0 .01-.03l-.001-.007L5.992 3.86a.05.05 0 0 0-.029-.01z"
          clipRule="evenodd"
        />
        <path d="m8.964 18.45 1.277-1.277c3.786 3.128 6.38 3.114 7.703 2.65.456-.17.858-.43 1.196-.77l1-1a.05.05 0 0 0 .01-.029v-.007l-3.072-3.072a.05.05 0 0 0-.03-.01h-.007l-1.524 1.525a2.19 2.19 0 0 1-2.332.504l-.043-.017-.064-.032a10.2 10.2 0 0 1-1.733-.845l1.317-1.318a8.4 8.4 0 0 0 1.088.493l.046.017.058.03c.138.04.282.004.39-.105l1.527-1.527c.708-.708 1.848-.687 2.553-.014l.007.007 3.095 3.094c.707.708.687 1.848.014 2.552l-.007.008-1.02 1.02a5.1 5.1 0 0 1-1.85 1.186l-.006.002-.008.003c-2.138.755-5.411.426-9.585-3.067" />
      </g>
    </svg>
  )
}
export default CallDeclineOutlineIcon
