/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function CallAcceptOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="CallAcceptOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="m5.905 3.9-1.01 1.01a3.1 3.1 0 0 0-.764 1.182l-.001.006c-.538 1.536-.481 4.756 4.283 9.504 4.76 4.743 7.96 4.804 9.48 4.271a3.3 3.3 0 0 0 1.197-.769l1-1a.05.05 0 0 0 .01-.037l-3.072-3.071a.05.05 0 0 0-.037-.01l-1.524 1.524a2.19 2.19 0 0 1-2.333.504l-.043-.016-.064-.032a10.27 10.27 0 0 1-5.993-5.993l-.032-.065-.016-.042a2.19 2.19 0 0 1 .504-2.333l1.514-1.515a.05.05 0 0 0 .01-.036L5.941 3.91a.05.05 0 0 0-.037-.01m-1.27-1.275c.708-.708 1.848-.687 2.552-.015l.008.008 3.094 3.094c.708.708.687 1.847.015 2.552l-.007.008-1.535 1.534a.39.39 0 0 0-.104.39l.03.059.016.046a8.47 8.47 0 0 0 4.995 4.994l.046.017.059.03c.137.04.281.005.39-.105l1.527-1.526c.708-.708 1.848-.687 2.552-.015l.008.007 3.094 3.094c.708.708.687 1.848.015 2.553l-.008.007-1.02 1.02a5.1 5.1 0 0 1-1.85 1.186l-.006.003-.007.002c-2.432.859-6.333.315-11.357-4.692-5.025-5.008-5.567-8.923-4.712-11.37a4.9 4.9 0 0 1 1.193-1.869z"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default CallAcceptOutlineIcon
