/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function CameraSwitchOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="CameraSwitchOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path d="M12.424 7.686a.65.65 0 0 1 .01.919l-.056.056c2.01.186 3.62 1.825 3.62 3.86a3.81 3.81 0 0 1-1.727 3.182.65.65 0 0 1-.718-1.084 2.51 2.51 0 0 0 1.145-2.098c0-1.202-.879-2.242-2.086-2.51a.649.649 0 0 1-1.107.55l-.959-.978a.65.65 0 0 1 0-.91l.959-.978a.65.65 0 0 1 .919-.01M11.083 14.433a.65.65 0 0 1 .92.01l.958.977a.65.65 0 0 1 0 .91l-.959.978a.65.65 0 0 1-1.01-.809c-1.737-.456-2.995-2.07-2.995-3.968 0-1.142.453-2.179 1.198-2.917a.65.65 0 0 1 .915.924 2.79 2.79 0 0 0-.813 1.993c0 1.162.674 2.142 1.623 2.568a.65.65 0 0 1 .163-.666" />
        <path
          fillRule="evenodd"
          d="M10 4a1 1 0 0 0-.707.293L7.586 6H5c-1.102 0-2 .898-2 2v10c0 1.102.898 2 2 2h14c1.102 0 2-.898 2-2V8c0-1.102-.898-2-2-2h-2.586l-1.707-1.707A1 1 0 0 0 14 4zM8.707 7.707 10.414 6h3.172l1.707 1.707A1 1 0 0 0 16 8h3v10H5V8h3a1 1 0 0 0 .707-.293"
          clipRule="evenodd"
        />
      </g>
    </svg>
  )
}
export default CameraSwitchOutlineIcon
