/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function CaptureOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="CaptureOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M3.25 4A.75.75 0 0 1 4 3.25h4a.75.75 0 0 1 0 1.5H4.75V8a.75.75 0 0 1-1.5 0zM12 7a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5m-5 9.101c0 .517.427.899.913.899H16.1c.465-.007.9-.378.9-.899v-.13a2.68 2.68 0 0 0-1.332-2.297l-.156-.093-.001-.001a6.93 6.93 0 0 0-7.022 0l-.157.094A2.68 2.68 0 0 0 7 15.97zM4 20.75a.75.75 0 0 1-.75-.75v-4a.75.75 0 0 1 1.5 0v3.25H8a.75.75 0 0 1 0 1.5zM20.75 4a.75.75 0 0 0-.75-.75h-4a.75.75 0 0 0 0 1.5h3.25V8a.75.75 0 0 0 1.5 0zM20 20.75a.75.75 0 0 0 .75-.75v-4a.75.75 0 0 0-1.5 0v3.25H16a.75.75 0 0 0 0 1.5z"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default CaptureOutlineIcon
