/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function CartFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="CartFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M2 4a1 1 0 0 1 1-1h1.149c.972 0 1.815.698 1.976 1.676v.002L6.345 6h12.154q.134 0 .26.016a2 2 0 0 1 1.6 2.72l-.002.005-1.198 2.996v.002A2 2 0 0 1 17.298 13H7.512l.332 1.995v.002l.003.002.002.001H17.99a1 1 0 0 1 0 2H7.846a2.01 2.01 0 0 1-1.976-1.675L4.152 5.004 4.15 5H2.999a1 1 0 0 1-1-1m6.995 15.5a1.5 1.5 0 1 1-2.999.001 1.5 1.5 0 0 1 3-.001m9.994 0a1.5 1.5 0 1 1-3 .001 1.5 1.5 0 0 1 3-.001"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default CartFillIcon
