/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ChatOffOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ChatOffOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M5.492 5.513C7.21 4.197 9.517 3.428 12 3.428c1.912 0 3.72.457 5.235 1.268l1.016-1.016a.857.857 0 0 1 1.212 1.212L4.035 20.32a.857.857 0 0 1-1.213-1.213l2.612-2.611-.08-.07c-1.645-1.311-2.783-3.203-2.783-5.402 0-2.262 1.201-4.195 2.92-5.512m1.154 9.771 9.31-9.31c-1.155-.527-2.508-.831-3.956-.831-2.14 0-4.072.664-5.466 1.732-1.394 1.067-2.248 2.535-2.248 4.15 0 1.571.808 3.003 2.136 4.063q.122.097.224.196m11.423-7.89 1.212-1.212c1.296 1.267 2.148 2.939 2.148 4.843 0 2.261-1.201 4.195-2.92 5.511-1.577 1.207-3.645 1.953-5.89 2.07-1.27 1.097-3.47 2.343-6.866 1.857a1.5 1.5 0 0 1-.558-.195l1.433-1.433c2.6.188 4.182-.878 5.063-1.7a.86.86 0 0 1 .564-.231c2.039-.05 3.873-.704 5.21-1.729 1.395-1.068 2.25-2.535 2.25-4.15 0-1.367-.613-2.628-1.646-3.63"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default ChatOffOutlineIcon
