/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ChatOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ChatOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M6.06 6.796C4.568 7.9 3.72 9.365 3.72 10.916c0 1.51.803 2.938 2.221 4.03.614.474 1 1.027 1.172 1.63.17.596.11 1.174-.05 1.673-.087.27-.206.525-.345.761 2.468-.06 3.934-1.17 4.73-1.941a.8.8 0 0 1 .552-.223c2.35 0 4.448-.706 5.94-1.81 1.492-1.103 2.34-2.568 2.34-4.12 0-1.551-.848-3.016-2.34-4.12-1.492-1.103-3.59-1.81-5.94-1.81s-4.448.707-5.94 1.81M5.115 5.55c1.79-1.324 4.227-2.12 6.885-2.12s5.095.796 6.885 2.12 2.972 3.214 2.972 5.367-1.182 4.044-2.972 5.368c-1.719 1.272-4.033 2.056-6.567 2.117-1.25 1.127-3.566 2.585-7.362 2.06a.775.775 0 0 1-.324-1.423c.262-.17.74-.676.928-1.262.089-.275.104-.536.035-.778-.068-.236-.234-.522-.624-.823-1.71-1.317-2.828-3.164-2.828-5.259 0-2.153 1.182-4.043 2.972-5.367"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default ChatOutlineIcon
