/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function DangerCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="DangerCircleOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path d="M12.75 8a.75.75 0 0 0-1.5 0v5a.75.75 0 0 0 1.5 0zM13 16a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
        <path
          fillRule="evenodd"
          d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18m0-1.5a7.5 7.5 0 1 0 0-15 7.5 7.5 0 0 0 0 15"
          clipRule="evenodd"
        />
      </g>
    </svg>
  )
}
export default DangerCircleOutlineIcon
