/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function DirectionCircleFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="DirectionCircleFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18m.633-13.64a.633.633 0 1 0-1.265 0v3.544l-3.07-1.772a.633.633 0 0 0-.633 1.096L10.735 12l-3.07 1.772a.633.633 0 1 0 .633 1.096l3.07-1.772v3.545a.633.633 0 1 0 1.265 0v-3.545l3.07 1.772a.633.633 0 1 0 .632-1.096L13.265 12l3.07-1.772a.633.633 0 1 0-.633-1.096l-3.069 1.772z"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default DirectionCircleFillIcon
