/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function DirectionCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="DirectionCircleOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M19.5 12a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0m1.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0m-8.437-4.125a.563.563 0 0 0-1.125 0v3.15L8.708 9.45a.563.563 0 0 0-.562.975L10.875 12l-2.729 1.575a.562.562 0 1 0 .563.975l2.729-1.576v3.151a.562.562 0 1 0 1.125 0v-3.15l2.728 1.575a.562.562 0 1 0 .563-.975L13.124 12l2.73-1.575a.562.562 0 1 0-.563-.975l-2.728 1.576z"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default DirectionCircleOutlineIcon
