/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function DuplicateOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="DuplicateOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path d="M11.25 8.5a.75.75 0 0 0-1.5 0v1.25H8.5a.75.75 0 0 0 0 1.5h1.25v1.25a.75.75 0 0 0 1.5 0v-1.25h1.25a.75.75 0 0 0 0-1.5h-1.25z" />
        <path
          fillRule="evenodd"
          d="M4 5.967C4 4.88 4.88 4 5.967 4h9.066C16.12 4 17 4.88 17 5.967v9.066C17 16.12 16.12 17 15.033 17H5.967A1.967 1.967 0 0 1 4 15.033zM6 6v9h9V6z"
          clipRule="evenodd"
        />
        <path d="M20 8.5a1 1 0 1 0-2 0v9.51H8.49a1 1 0 1 0 0 2h9.63c1.05 0 1.88-.855 1.88-1.88z" />
      </g>
    </svg>
  )
}
export default DuplicateOutlineIcon
