/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ExitOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ExitOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        d="M5 21q-.824 0-1.412-.587A1.93 1.93 0 0 1 3 19V5q0-.824.587-1.412A1.93 1.93 0 0 1 5 3h6a1 1 0 1 1 0 2H5v14h6a1 1 0 1 1 0 2zm11.725-4.725a.999.999 0 0 1-1.412-1.413L17.175 13H10a1 1 0 1 1 0-2h7.175l-1.862-1.862a.999.999 0 0 1 1.412-1.413l3.568 3.568a1 1 0 0 1 0 1.414z"
      />
    </svg>
  )
}
export default ExitOutlineIcon
