/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function FavoriteFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="FavoriteFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        d="M7.636 20.444c-.796.48-1.777-.233-1.568-1.137l1.149-4.965-3.853-3.34c-.702-.609-.327-1.762.598-1.842l5.095-.442 1.975-4.674c.361-.856 1.575-.856 1.936 0l1.976 4.674 5.094.442c.925.08 1.3 1.233.598 1.841l-3.853 3.34 1.149 4.966c.209.904-.772 1.616-1.568 1.137L12 17.81z"
      />
    </svg>
  )
}
export default FavoriteFillIcon
