/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function HistoryOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="HistoryOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        d="M12 20q-2.8 0-4.956-1.7-2.155-1.699-2.8-4.344a.66.66 0 0 1 .134-.611.87.87 0 0 1 .6-.323.97.97 0 0 1 .644.134.92.92 0 0 1 .4.533q.534 2 2.2 3.267A6.08 6.08 0 0 0 12 18.222q2.6 0 4.412-1.81 1.81-1.812 1.81-4.412 0-2.601-1.81-4.41T12 5.777a6 6 0 0 0-2.867.71A6.6 6.6 0 0 0 6.89 8.445h1.555a.86.86 0 0 1 .634.256q.256.256.255.633a.87.87 0 0 1-.256.634.85.85 0 0 1-.633.255H4.89a.86.86 0 0 1-.633-.256A.86.86 0 0 1 4 9.333V5.778q0-.378.256-.633a.86.86 0 0 1 .633-.256q.376 0 .634.256a.85.85 0 0 1 .255.633v1.2a7.76 7.76 0 0 1 2.767-2.2A7.94 7.94 0 0 1 12 4q1.666 0 3.123.634 1.455.633 2.533 1.71a8.1 8.1 0 0 1 1.711 2.533Q20.002 10.334 20 12q0 1.665-.633 3.123a8.1 8.1 0 0 1-1.711 2.533 8.2 8.2 0 0 1-2.533 1.711A7.7 7.7 0 0 1 12 20m.889-8.356 2.222 2.223q.245.244.245.622 0 .379-.245.622a.84.84 0 0 1-.622.245.84.84 0 0 1-.622-.245l-2.49-2.489a.89.89 0 0 1-.266-.644V8.444q0-.377.256-.632A.86.86 0 0 1 12 7.556q.377-.002.634.256a.85.85 0 0 1 .255.632z"
      />
    </svg>
  )
}
export default HistoryOutlineIcon
