/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function HomeOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="HomeOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="m18 9.97-6-4.563L6 9.97v9.127h12zM4.4 8.652c-.252.191-.4.492-.4.811v10.648c0 .56.448 1.014 1 1.014h14c.552 0 1-.454 1-1.014V9.463c0-.32-.148-.62-.4-.811l-7-5.324a.99.99 0 0 0-1.2 0z"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default HomeOutlineIcon
