/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function LikeOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="LikeOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M11.428 4.383a.79.79 0 0 1 .894-.353l.456.13a3.16 3.16 0 0 1 2.157 3.944l-.19.633h2.887A2.37 2.37 0 0 1 20 11.105v.503c0 .284-.051.566-.15.832l-1.692 4.51A3.16 3.16 0 0 1 15.2 19H5.789A.79.79 0 0 1 5 18.21V8.737a.79.79 0 0 1 .79-.79h3.5zm1.04 1.337-2.054 3.423a.79.79 0 0 1-.677.383H6.579v7.895H15.2c.658 0 1.247-.408 1.478-1.024l1.692-4.511a.8.8 0 0 0 .05-.277v-.504a.79.79 0 0 0-.79-.79h-3.947a.79.79 0 0 1-.756-1.015l.495-1.65a1.58 1.58 0 0 0-.955-1.93"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default LikeOutlineIcon
