/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function LinkOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="LinkOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M9.711 14.289q.387.386.837.66a.938.938 0 1 0 .98-1.6 2.7 2.7 0 0 1-.49-.387c-1.07-1.07-1.07-2.911.133-4.115l2.389-2.389c1.204-1.203 3.045-1.202 4.114-.132 1.07 1.069 1.071 2.91-.133 4.114l-1.194 1.194a.938.938 0 1 0 1.327 1.328l1.195-1.195c1.875-1.875 1.995-4.906.132-6.769-1.862-1.862-4.893-1.742-6.768.133L9.843 7.52c-1.874 1.875-1.995 4.906-.132 6.769m3.982-3.982a5 5 0 0 0-.831-.666.938.938 0 1 0-1.005 1.585q.27.171.509.408c1.123 1.124 1.12 2.862.1 3.883l-2.19 2.19c-1.022 1.02-2.76 1.024-3.883-.1s-1.12-2.861-.1-3.882L7.39 12.63a.938.938 0 1 0-1.328-1.327l-1.095 1.095c-1.8 1.8-1.708 4.728.1 6.536s4.735 1.9 6.536.1l2.19-2.19c1.802-1.801 1.71-4.728-.1-6.537"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default LinkOutlineIcon
