/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function LockOnOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="LockOnOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path
          fillRule="evenodd"
          d="M12 3a5 5 0 0 0-5 5v1h-.25C5.687 9 5 9.923 5 10.833v8.334C5 20.077 5.687 21 6.75 21h10.5c1.063 0 1.75-.922 1.75-1.833v-8.334C19 9.923 18.313 9 17.25 9H17V8a5 5 0 0 0-5-5m3 6V8a3 3 0 1 0-6 0v1zm-8 2v8h10v-8z"
          clipRule="evenodd"
        />
        <path d="M13.5 15a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0" />
      </g>
    </svg>
  )
}
export default LockOnOutlineIcon
