/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function LoveitOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="LoveitOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M8.4 5.826c-1.077 0-1.934.333-2.622.982C5.09 7.455 4.75 8.245 4.75 9.23q0 .732.264 1.44c.17.457.487.997.978 1.619.49.621 1.162 1.338 2.026 2.152a88 88 0 0 0 3.31 2.932l.672.567.671-.567a88 88 0 0 0 3.311-2.932c.864-.814 1.536-1.53 2.026-2.152.491-.622.807-1.162.979-1.62q.264-.707.263-1.439c0-.985-.34-1.775-1.028-2.422-.688-.649-1.545-.982-2.622-.982a4.1 4.1 0 0 0-3.04 1.334.754.754 0 0 1-1.12 0A4.096 4.096 0 0 0 8.4 5.825m-3.658-.09c.992-.934 2.229-1.392 3.658-1.392A5.6 5.6 0 0 1 12 5.635q.592-.494 1.314-.812a5.6 5.6 0 0 1 2.286-.48c1.43 0 2.666.459 3.658 1.393.993.935 1.492 2.117 1.492 3.494q0 1.002-.357 1.953c-.242.647-.652 1.32-1.201 2.017-.55.697-1.278 1.469-2.174 2.313a89 89 0 0 1-3.37 2.984l-1.16.982a.76.76 0 0 1-.975 0l-1.16-.98-.002-.002a89 89 0 0 1-3.369-2.984c-.896-.844-1.624-1.616-2.174-2.313s-.96-1.37-1.202-2.017A5.5 5.5 0 0 1 3.25 9.23c0-1.377.5-2.559 1.492-3.494"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default LoveitOutlineIcon
