/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ManagerCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ManagerCircleOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor" fillRule="evenodd" clipRule="evenodd">
        <path d="M12 7.5a.936.936 0 0 0-.726 1.508l-1.352 1.845-1.706-.652a.927.927 0 0 0-.919-.851.93.93 0 0 0-.922.933c0 .442.304.812.712.908l.855 3.892v1.013c0 .223.18.404.4.404h7.315c.221 0 .4-.181.4-.404v-1.013l.855-3.892a.93.93 0 0 0 .713-.908.93.93 0 0 0-.922-.933.927.927 0 0 0-.92.85l-1.706.653-1.351-1.844a.94.94 0 0 0 .196-.576A.93.93 0 0 0 12 7.5m-3.337 7.134h6.674l.795-3.619a1 1 0 0 1-.066-.057l-1.989.76a.4.4 0 0 1-.462-.138L12 9.376l-1.616 2.204a.4.4 0 0 1-.462.137l-1.988-.76a1 1 0 0 1-.066.059z" />
        <path d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18m0-1.5a7.5 7.5 0 1 0 0-15 7.5 7.5 0 0 0 0 15" />
      </g>
    </svg>
  )
}
export default ManagerCircleOutlineIcon
