/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ModelFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ModelFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path d="M10 5a2 2 0 1 1 4 0 2 2 0 0 1-4 0M4 9a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2h-4v10a1 1 0 1 1-2 0v-5h-2v5a1 1 0 1 1-2 0V10H5a1 1 0 0 1-1-1" />
      </g>
    </svg>
  )
}
export default ModelFillIcon
