/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function MyCircleOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="MyCircleOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path d="M6.068 9.545c0-.338.275-.613.614-.613h.357c.23 0 .44.128.545.332L9.359 12.7l1.776-3.436a.61.61 0 0 1 .545-.332h.357c.339 0 .614.275.614.613v4.686a.614.614 0 0 1-1.227 0V11.38l-1.52 2.939a.614.614 0 0 1-1.09 0l-1.519-2.94v2.853a.614.614 0 1 1-1.227 0zM18.292 9.646a.614.614 0 0 1 .339.799l-1.903 4.704-.014.033c-.323.683-.73 1.183-1.243 1.453-.53.28-1.084.267-1.583.095a.614.614 0 0 1 .398-1.16c.246.084.439.071.612-.02.161-.086.366-.27.58-.649l-1.992-4.435a.614.614 0 1 1 1.12-.503l1.524 3.393 1.363-3.371a.614.614 0 0 1 .799-.34" />
        <path
          fillRule="evenodd"
          d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18m0-1.5a7.5 7.5 0 1 0 0-15 7.5 7.5 0 0 0 0 15"
          clipRule="evenodd"
        />
      </g>
    </svg>
  )
}
export default MyCircleOutlineIcon
