/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function NotificationOnOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="NotificationOnOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M11.538 3.857c-3 0-5.43 2.432-5.43 5.431v1.39c0 .309-.121.605-.336.825a4.86 4.86 0 0 0-1.38 3.39v.955c0 .833.677 1.51 1.51 1.51h2.82a3.322 3.322 0 0 0 6.557 0h2.819a1.51 1.51 0 0 0 1.51-1.51v-.956a4.85 4.85 0 0 0-1.38-3.389 1.18 1.18 0 0 1-.335-.825v-1.39c0-3-2.432-5.43-5.43-5.43zm2.203 13.5H10.26a1.822 1.822 0 0 0 3.482 0M7.607 9.288c0-2.171 1.76-3.93 3.931-3.93h.924a3.93 3.93 0 0 1 3.93 3.93v1.39c0 .7.274 1.372.762 1.872.611.627.953 1.467.953 2.342v.959l-.002.003-.004.003H5.9l-.003-.003-.003-.003v-.959c0-.875.342-1.715.953-2.342.488-.5.761-1.172.761-1.872z"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default NotificationOnOutlineIcon
