/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function NotificationOffOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="NotificationOffOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor" fillRule="evenodd" clipRule="evenodd">
        <path d="M11.61 3.857c-3 0-5.431 2.432-5.431 5.431v1.39c0 .309-.12.605-.336.825a4.86 4.86 0 0 0-1.379 3.39v.955c0 .465.21.88.541 1.158l-.464.464a.75.75 0 0 0 1.06 1.06l13-13a.75.75 0 0 0-1.06-1.06l-1.074 1.074a5.42 5.42 0 0 0-3.933-1.687zm3.796 2.748a3.92 3.92 0 0 0-2.873-1.248h-.923a3.93 3.93 0 0 0-3.931 3.931v1.39c0 .7-.274 1.372-.762 1.872a3.36 3.36 0 0 0-.953 2.342v.959l.003.003.003.003h.184zM8.793 17.357h-.447l1.5-1.5h8.327l.005-.005v-.96c0-.875-.341-1.715-.952-2.341a2.68 2.68 0 0 1-.762-1.873V9.24l1.325-1.326c.114.44.175.9.175 1.374v1.39c0 .309.12.605.336.825a4.85 4.85 0 0 1 1.379 3.39v.955a1.51 1.51 0 0 1-1.51 1.51h-2.82a3.322 3.322 0 0 1-6.556 0m5.02 0H10.33a1.822 1.822 0 0 0 3.483 0" />
      </g>
    </svg>
  )
}
export default NotificationOffOutlineIcon
