/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function PlayOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="PlayOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M17.958 12 7.5 6.074v11.852zM8.24 4.77l10.457 5.925a1.5 1.5 0 0 1 0 2.61L8.24 19.231A1.5 1.5 0 0 1 6 17.926V6.074A1.5 1.5 0 0 1 8.24 4.77"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default PlayOutlineIcon
