/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function PlayFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="PlayFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        d="M18.697 10.695 8.24 4.769A1.5 1.5 0 0 0 6 6.074v11.852a1.5 1.5 0 0 0 2.24 1.305l10.457-5.926a1.5 1.5 0 0 0 0-2.61"
      />
    </svg>
  )
}
export default PlayFillIcon
