/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function QuestionOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="QuestionOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path d="M12 19a1.25 1.25 0 1 0 0-2.5 1.25 1.25 0 0 0 0 2.5" />
        <path
          fillRule="evenodd"
          d="M10.966 4.064c1.352-.236 2.815.111 3.9 1.08l.003.003c1.708 1.537 1.84 4.068.273 5.745-.377.405-.856.848-1.298 1.255-.19.174-.371.342-.535.498l-.006.006c-.117.11-.19.18-.244.237l-.053.06a1 1 0 0 0-.006.122v1.42a1 1 0 1 1-2 0v-1.42c0-.381.057-.757.277-1.129.178-.3.437-.543.638-.731l.02-.018q.322-.305.628-.586c.411-.378.791-.728 1.114-1.076l.003-.004c.79-.843.743-2.089-.147-2.891-.593-.528-1.425-.742-2.23-.6l-.01.002-.011.001a3 3 0 0 0-.3.089C9.89 6.505 9.24 7.457 9.24 8.46v.19a1 1 0 1 1-2 0v-.19c0-1.895 1.229-3.583 3.094-4.225l.01-.004c.165-.055.399-.132.622-.167"
          clipRule="evenodd"
        />
      </g>
    </svg>
  )
}
export default QuestionOutlineIcon
