/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ReportOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ReportOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M12.902 6.514a2.49 2.49 0 0 0-2.723-.751l-2.554.89v6.075l2.558-.822a4.04 4.04 0 0 1 4.335 1.252 2.42 2.42 0 0 0 2.857.645V7.766a4.11 4.11 0 0 1-4.473-1.252m-5.277 7.92 3.056-.982c.935-.3 1.96-.005 2.591.749a4.04 4.04 0 0 0 4.969.986l.323-.168a.81.81 0 0 0 .436-.72V6.532a.812.812 0 0 0-1.145-.742l-.787.353a2.486 2.486 0 0 1-2.92-.672 4.11 4.11 0 0 0-4.503-1.242l-3.1 1.079A.81.81 0 0 0 6 6.075v12.793a.812.812 0 0 0 1.625 0z"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default ReportOutlineIcon
