/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ResetOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ResetOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path d="M13.457 2.793a1 1 0 0 1 0 1.414l-.818.818A7.995 7.995 0 0 1 20 13a8.005 8.005 0 0 1-5.715 7.669 1 1 0 0 1-.57-1.918A6.005 6.005 0 0 0 18 13c0-3.08-2.31-5.611-5.295-5.96l.752.753a1 1 0 0 1-1.414 1.414l-2.5-2.5a1 1 0 0 1 0-1.414l2.5-2.5a1 1 0 0 1 1.414 0M7.8 8.713a1 1 0 1 0-1.4-1.426A8.02 8.02 0 0 0 4 13.029a8.03 8.03 0 0 0 6.856 7.96 1 1 0 1 0 .288-1.979A6.03 6.03 0 0 1 6 13.03c0-1.696.686-3.222 1.8-4.317" />
      </g>
    </svg>
  )
}
export default ResetOutlineIcon
