/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function SaveOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="SaveOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        d="M19.5 7.333v10q0 .688-.49 1.177-.489.49-1.177.49H6.167q-.688 0-1.177-.49a1.6 1.6 0 0 1-.49-1.177V5.667q0-.688.49-1.177Q5.479 4 6.167 4h10zm-1.667.709-2.375-2.375H6.167v11.666h11.666zM12 15.667q1.042 0 1.77-.73.73-.729.73-1.77 0-1.042-.73-1.771a2.4 2.4 0 0 0-1.77-.73 2.4 2.4 0 0 0-1.77.73 2.4 2.4 0 0 0-.73 1.77q0 1.042.73 1.771.728.73 1.77.73M7 7.333c0 .46.373.834.833.834H12A.833.833 0 0 0 12 6.5H7.833A.833.833 0 0 0 7 7.333"
      />
    </svg>
  )
}
export default SaveOutlineIcon
