/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function SearchFillIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="SearchFillIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        d="M10 3a7 7 0 1 0 4.2 12.6 1 1 0 0 0 .093.107l4 4a1 1 0 0 0 1.414-1.414l-4-4a1 1 0 0 0-.107-.093A7 7 0 0 0 10 3"
      />
    </svg>
  )
}
export default SearchFillIcon
