/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function SendOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="SendOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M17.394 4.934c1.144-.385 2.27.741 1.885 1.885l-4.33 12.843a1.38 1.38 0 0 1-1.249.945 1.5 1.5 0 0 1-1.384-.762l-.007-.012-1.848-3.448a1.45 1.45 0 0 1 .053-1.535l2.064-3.215L9.363 13.7a1.45 1.45 0 0 1-1.534.053L4.38 11.904l-.012-.007a1.5 1.5 0 0 1-.761-1.384 1.38 1.38 0 0 1 .945-1.25zm.937 1.565c.122-.36-.258-.738-.617-.617L4.87 10.212a.38.38 0 0 0-.266.356c-.01.168.07.35.255.458l3.447 1.848.012.006a.45.45 0 0 0 .496-.018l5.152-3.307a.5.5 0 0 1 .691.691l-3.307 5.152-.012.017a.45.45 0 0 0-.006.479l.007.012 1.847 3.447c.109.186.29.264.458.255.166-.009.3-.1.357-.266z"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default SendOutlineIcon
