/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function SkeletonOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="SkeletonOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M12 6c-3.367 0-6 2.567-6 5.618 0 1.813.92 3.442 2.378 4.478a1 1 0 0 1 .421.816V19a1 1 0 1 1-2 0v-1.593C5.097 16.018 4 13.947 4 11.617 4 7.359 7.635 4 12 4s8 3.358 8 7.618c0 2.33-1.097 4.4-2.8 5.789V19a1 1 0 1 1-2 0v-2.088a1 1 0 0 1 .422-.816C17.08 15.06 18 13.432 18 11.619 18 8.568 15.367 6 12 6m1 10.25a.75.75 0 0 1 .75.75v2a.75.75 0 0 1-1.5 0v-2a.75.75 0 0 1 .75-.75m-1.25.75a.75.75 0 0 0-1.5 0v2a.75.75 0 0 0 1.5 0zm2.75-4.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5m2.25-.75a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0m-6.5 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0m-.75 2.25a2.25 2.25 0 1 0 0-4.5 2.25 2.25 0 0 0 0 4.5"
        clipRule="evenodd"
      />
    </svg>
  )
}
export default SkeletonOutlineIcon
