/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function UndoOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="UndoOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <path
        fill="currentColor"
        d="M9.207 5.707a1 1 0 0 0-1.414-1.414l-3.5 3.5a1 1 0 0 0 0 1.414l3.5 3.5a1 1 0 0 0 1.414-1.414L7.414 9.5h6.336a4.25 4.25 0 1 1 0 8.5H5a1 1 0 1 0 0 2h8.75A6.25 6.25 0 0 0 20 13.75a6.25 6.25 0 0 0-6.25-6.25H7.414z"
      />
    </svg>
  )
}
export default UndoOutlineIcon
