/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function UploadOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="UploadOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path d="M19 2a1 1 0 0 1 1 1v1h1a1 1 0 1 1 0 2h-1v1a1 1 0 1 1-2 0V6h-1a1 1 0 1 1 0-2h1V3a1 1 0 0 1 1-1M6 6h7.746a1 1 0 1 0 0-2H5.871C4.838 4 4 4.839 4 5.871V18.13C4 19.16 4.837 20 5.87 20H18.13c1.033 0 1.87-.839 1.87-1.871v-7.882a1 1 0 1 0-2 0V18H6z" />
        <path d="M7.418 17h9.09c.378 0 .597-.41.358-.69l-2.69-3.15a.473.473 0 0 0-.718.01l-1.994 2.49a.472.472 0 0 1-.747-.02L9.61 14.08a.472.472 0 0 0-.748-.02L7.06 16.31c-.229.28-.01.68.369.68z" />
      </g>
    </svg>
  )
}
export default UploadOutlineIcon
