/**
 * DO NOT EDIT - automatically generated by script
 */
import { CSSProperties, SVGProps } from 'react'
type Props = SVGProps<SVGSVGElement> & {
  size?: number,
  color?: CSSProperties['color'],
}
function ZoonInOutlineIcon({ size = 24, color = 'currentColor', ...props }: Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      id="ZoonInOutlineIcon"
      width={size}
      height={size}
      color={color}
      strokeWidth="0"
      {...props}
    >
      <g fill="currentColor">
        <path d="M10 7a.75.75 0 0 1 .75.75v1.5h1.5a.75.75 0 0 1 0 1.5h-1.5v1.5a.75.75 0 0 1-1.5 0v-1.5h-1.5a.75.75 0 0 1 0-1.5h1.5v-1.5A.75.75 0 0 1 10 7" />
        <path
          fillRule="evenodd"
          d="M10 3a7 7 0 1 0 4.2 12.6 1 1 0 0 0 .093.107l4 4a1 1 0 0 0 1.414-1.414l-4-4a1 1 0 0 0-.107-.093A7 7 0 0 0 10 3m-5 7a5 5 0 1 1 10 0 5 5 0 0 1-10 0"
          clipRule="evenodd"
        />
      </g>
    </svg>
  )
}
export default ZoonInOutlineIcon
